export const DEMO_USER = {
  id: 'usr_89234798',
  firstName: 'Alex',
  lastName: 'Rivera',
  email: 'alex.rivera@architect.com',
  role: 'Principal System Architect',
  company: 'TechCloud Neural Labs',
  bio: 'Designing fault-tolerant microservice meshes & AI neural pipelines.',
  isVerified: true,
  twoFactorEnabled: true,
  createdAt: '2026-01-15T08:30:00.000Z',
};

export const INITIAL_NODES = [
  {
    id: 'node-1',
    name: 'Edge API Gateway',
    type: 'api-gateway',
    status: 'healthy',
    latency: 8,
    cpu: 24,
    memory: 42,
    x: 30,
    y: 60,
  },
  {
    id: 'node-2',
    name: 'Gemini AI Neural Engine',
    type: 'ai-model',
    status: 'healthy',
    latency: 18,
    cpu: 68,
    memory: 74,
    x: 230,
    y: 30,
  },
  {
    id: 'node-3',
    name: 'Auth & Session Service',
    type: 'microservice',
    status: 'healthy',
    latency: 12,
    cpu: 31,
    memory: 50,
    x: 230,
    y: 130,
  },
  {
    id: 'node-4',
    name: 'Redis Cache Layer',
    type: 'redis',
    status: 'healthy',
    latency: 2,
    cpu: 15,
    memory: 38,
    x: 430,
    y: 30,
  },
  {
    id: 'node-5',
    name: 'Primary PostgreSQL Cluster',
    type: 'database',
    status: 'healthy',
    latency: 14,
    cpu: 45,
    memory: 62,
    x: 430,
    y: 130,
  },
];
